### ISSUE TITLE
README

### ISSUE THREAD

**Issue by rossholdway** [danteissaias/fast#5]
This looks great, really like the simplicity of it all. I think if you could update the README with some nice documentation it’d help to get more people using the project. Thanks!

**Comment by danteissaias** [comment]
I will write some documentation for the next release. In the meantime the [`examples/`](https://github.com/danteissaias/fast/tree/main/examples) folder contains some small examples of core features.

**Comment by Abiti-936** [comment]
Try to Add JsDoc Comments to get some code snippets with editor completions.

**Comment by danteissaias** [comment]
@Abiti-936 I would appreciate if someone could contribute some comments/documentation.
