### ISSUE TITLE
More Middlewares with Configurability

### ISSUE THREAD

**Issue by Abiti-936** [danteissaias/fast#8]
It's really great to have a web framework that's simple & fast.

I think we can push "fast" forward by implementing more Middlewares like Etag, Logging, Jwt Auth, GraphQL & more... with more configuration options.

Also It's good to have some more examples. Thanks.

**Comment by danteissaias** [comment]
Feel free to open a PR.

**Comment by Abiti-936** [comment]
Ok, Great. I will let you know. 
Also what do you think about a simple docs website for fast. we can build it with [Lume](https://github.com/lumeland/lume) or [Fresh](https://github.com/denoland/fresh) or Something like that.

**Comment by danteissaias** [comment]
> Also what do you think about a simple docs website for fast. we can build it with [Lume](https://github.com/lumeland/lume) or [Fresh](https://github.com/denoland/fresh). what do you think?

For now let's start with JSDoc annotations. However it would be good to have a dedicated site in the near future.

**Comment by danteissaias** [comment]
> Ok, Great. I will let you know.

Write tests for any new middleware.

**Comment by danteissaias** [comment]
See #5 - this was delayed a bit but I am working on some documentation.

**Comment by danteissaias** [comment]
I am working on a web framework that uses fast under the hood. So it would be good to write the documentation site with that when it's ready.

**Comment by Abiti-936** [comment]
I think we should add some more middleware's like

**Comment by Abiti-936** [comment]
Now we have an Etag & CORS Middlewares, we should work on bringing other types of middlewares like Static Web Sites Serving Middleware, and more...

**Comment by danteissaias** [comment]
We have a static file serving middleware however it lacks configuration options.

**Comment by Abiti-936** [comment]
I will create a PR when I have finished testing it, but just take a look at it in here:
https://github.com/Abiti-936/fast/blob/static-middleware/middleware/static-server.ts

**Comment by danteissaias** [comment]
My original goal with fast was to keep the codebase small. I no longer think bundling middleware is aligned with this goal. Feel free to create your own repo for fast middleware.
